/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lab10;

import java.io.File;
import java.util.EventObject;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author carol
 */
public class GamePanel extends javax.swing.JPanel {

    private Game game;
    private Viewable controller;
    private SudokuUndoManager undoManager;

    /**
     * Creates new form ShowGamePanel
     */
    public GamePanel(Game game, Viewable controller) {
        this.game = game;
        this.controller = controller;
        File logFile = new File("incomplete/log.txt");
        undoManager = new SudokuUndoManager(logFile);
        initComponents();
        fillTable();
        configureEditors();
        updateSolveButtonState();
    }

    public void fillTable() {
        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                int value = game.getValue(row, col);
                if (value != 0) {
                    sudokuTable.setValueAt(value, row, col);
                } else {
                    sudokuTable.setValueAt("", row, col);
                }
            }
        }
    }

    private void configureEditors() {
        JTextField tf = new JTextField();
        ((AbstractDocument) tf.getDocument()).setDocumentFilter(new DigitFilter());

        tf.getDocument().addUndoableEditListener(new UndoableEditListener() {
            @Override
            public void undoableEditHappened(UndoableEditEvent e) {
            }
        });

        sudokuTable.setDefaultEditor(Object.class, new DefaultCellEditor(tf) {
            @Override
            public boolean isCellEditable(EventObject e) {
                int row = sudokuTable.getSelectedRow();
                int col = sudokuTable.getSelectedColumn();
                return game.getValue(row, col) == 0;
            }
        });
    }

    private void updateGameFromTable() {
        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                Object cellValue = sudokuTable.getValueAt(row, col);
                int newValue = 0;
                if (cellValue != null) {
                    String text = cellValue.toString().trim();
                    if (!text.isEmpty()) {
                        try {
                            newValue = Integer.parseInt(text);
                        } catch (NumberFormatException e) {
                        }
                    }
                }
                int oldValue = game.getValue(row, col);
                if (oldValue != newValue) {
                    undoManager.recordMove(game, row, col, oldValue, newValue);
                    game.setValue(row, col, newValue);
                }
            }
        }
        updateSolveButtonState();
    }

    private void updateSolveButtonState() {
        int emptyCount = 0;
        for (int row = 0; row < 9; row++) {
            for (int col = 0; col < 9; col++) {
                Object cellValue = sudokuTable.getValueAt(row, col);
                if (cellValue == null || cellValue.toString().trim().isEmpty()) {
                    emptyCount++;
                }
            }
        }
        solveButton.setEnabled(emptyCount == 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verifyButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sudokuTable = new javax.swing.JTable();

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });

        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        sudokuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(sudokuTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(verifyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(solveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undoButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyButton)
                    .addComponent(solveButton)
                    .addComponent(undoButton))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
        updateGameFromTable();
        boolean[][] invalidCells = controller.verifyGame(game.toMatrix());
        highlightInvalidCells(invalidCells);

    }//GEN-LAST:event_verifyButtonActionPerformed

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        updateGameFromTable();
        controller.solveGame();
        fillTable();
    }//GEN-LAST:event_solveButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        undoManager.undo(game);
        fillTable();
        updateSolveButtonState();
    }//GEN-LAST:event_undoButtonActionPerformed
    private void highlightInvalidCells(boolean[][] invalidCells) {
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                if (invalidCells[r][c]) {
                    sudokuTable.setValueAt("X", r, c);
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton solveButton;
    private javax.swing.JTable sudokuTable;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
