/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab10;

import javax.swing.JOptionPane;

/**
 *
 * @author carol
 */
public class StartGame extends javax.swing.JFrame {

    private Viewable controller;
    private GameLoader loader;
    private Game game;

    /**
     * Creates new form StartUp
     */
    public StartGame(Viewable controller, GameLoader loader) {
        this.controller = controller;
        this.loader = loader;
        initComponents();
        startButton.addActionListener(e -> {
            Catalog catalog = controller.getCatalog();
            handleCatalog(catalog);
        });
        this.game = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeText = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        welcomeText.setText("Welcome to the Sudoku Game");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

    }//GEN-LAST:event_startButtonActionPerformed
    public void handleCatalog(Catalog catalog) {
        if (catalog.isCurrentValid()) {
            try {
                game = loader.loadIncomplete();
                showGamePanel(game);
            } catch (IllegalStateException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Folder Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else if (catalog.doAllModesExist()) {
            String[] options = {"Easy", "Medium", "Hard"};
            String choice = (String) JOptionPane.showInputDialog(
                    this,
                    "Choose difficulty:",
                    "Difficulty Selection",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
            );

            if (choice != null) {
                game = loader.load(choice.toLowerCase());
                showGamePanel(game);
            }

        } else {
            String path = JOptionPane.showInputDialog(
                    this,
                    "No games available. Please provide the path to a solved Sudoku file:",
                    "Provide Sudoku File",
                    JOptionPane.QUESTION_MESSAGE
            );

            if (path != null && !path.isEmpty()) {
                try {
                    Game solvedGame = loader.loadSolvedBoard(path);
                    controller.driveGames(solvedGame);
                    String[] options = {"Easy", "Medium", "Hard"};
                    String choice = (String) JOptionPane.showInputDialog(
                            this,
                            "Games generated successfully! Choose difficulty:",
                            "Difficulty Selection",
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[0]
                    );

                    if (choice != null) {
                        game = loader.load(choice.toLowerCase());
                        showGamePanel(game);
                    }

                } catch (SolutionInvalidException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Provided solution is invalid or incomplete.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void showGamePanel(Game game) {
        GamePanel gp = new GamePanel(game, controller);
        getContentPane().removeAll();
        getContentPane().add(gp);
        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startButton;
    private javax.swing.JTextField welcomeText;
    // End of variables declaration//GEN-END:variables
}
